### ISSUE TITLE
sr replaced by '^2'

### ISSUE THREAD

**Issue by miguel9554** [ckunte/latex-snippets-vim#1]
On tex files, whenever I write `sr` in insert mode, it gets replaced by `^2`

Disabling this plugin fixes the issue, so I'm concluding it is the responsable

**Comment by ckunte** [comment]
> On tex files, whenever I write `sr` in insert mode, it gets replaced by `^2`

Thank you for reporting. Understand. I have disabled auto-triggerring for a couple of snippets. Now to get the square, for example, one needs to type `sr` + <kbd>tab</kbd> to get `^2`.
